/* ###################################################################
 **     This component module is generated by Processor Expert. Do not modify it.
 **     Filename    : pin_mux.c
 **     Project     : SignalGenerator
 **     Processor   : MK22FN512VLH12
 **     Component   : PinSettings
 **     Version     : Component 01.007, Driver 1.1, CPU db: 3.00.000
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2015-03-11, 15:56, # CodeGen: 0
 **     Abstract    :
 **
 **     Settings    :
 **
 **     Contents    :
 **         hardware_init       - void hardware_init(void);
 **         configure_ftm_pins  - void configure_ftm_pins(uint32_t instance);
 **         configure_gpio_pins - void configure_gpio_pins(uint32_t instance);
 **         configure_i2c_pins  - void configure_i2c_pins(uint32_t instance);
 **         configure_i2s_pins  - void configure_i2s_pins(uint32_t instance);
 **         configure_jtag_pins - void configure_jtag_pins(uint32_t instance);
 **         configure_llwu_pins - void configure_llwu_pins(uint32_t instance);
 **         configure_osc_pins  - void configure_osc_pins(uint32_t instance);
 **         configure_rtc_pins  - void configure_rtc_pins(uint32_t instance);
 **         configure_spi_pins  - void configure_spi_pins(uint32_t instance);
 **         configure_uart_pins - void configure_uart_pins(uint32_t instance);
 **
 **     Copyright : 1997 - 2014 Freescale Semiconductor, Inc.
 **     All Rights Reserved.
 **
 **     Redistribution and use in source and binary forms, with or without modification,
 **     are permitted provided that the following conditions are met:
 **
 **     o Redistributions of source code must retain the above copyright notice, this list
 **       of conditions and the following disclaimer.
 **
 **     o Redistributions in binary form must reproduce the above copyright notice, this
 **       list of conditions and the following disclaimer in the documentation and/or
 **       other materials provided with the distribution.
 **
 **     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 **       contributors may be used to endorse or promote products derived from this
 **       software without specific prior written permission.
 **
 **     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 **     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 **     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 **     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 **     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 **     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 **     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 **     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 **     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 **     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **
 **     http: www.freescale.com
 **     mail: support@freescale.com
 ** ###################################################################*/
/*!
 ** @file pin_mux.c
 ** @version 1.1
 ** @brief
 **
 */
/*!
 **  @addtogroup pin_mux_module pin_mux module documentation
 **  @{
 */

/* MODULE pin_mux. */

#include "pin_mux.h"
#include "PE_Types.h"
#include "IO_Map.h"

/*
 ** ===================================================================
 **     Method      :  pin_mux_hardware_init (component PinSettings)
 */
/*!
 **     @brief
 **         This method sets registers according routing settings. Call
 **         this method in user code to route desired pins into
 **         peripherals. The method is useful for reinitialization HW
 **         after some routing changes.
 */
/* ===================================================================*/
void pin_mux_hardware_init(void)
{
	/* DMAMUX_CHCFG0: SOURCE=0 */
	DMAMUX_CHCFG0 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG1: SOURCE=0 */
	DMAMUX_CHCFG1 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG2: SOURCE=0 */
	DMAMUX_CHCFG2 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG3: SOURCE=0 */
	DMAMUX_CHCFG3 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG4: SOURCE=0 */
	DMAMUX_CHCFG4 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG5: SOURCE=0 */
	DMAMUX_CHCFG5 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG6: SOURCE=0 */
	DMAMUX_CHCFG6 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG7: SOURCE=0 */
	DMAMUX_CHCFG7 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG8: SOURCE=0 */
	DMAMUX_CHCFG8 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG9: SOURCE=0 */
	DMAMUX_CHCFG9 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG10: SOURCE=0 */
	DMAMUX_CHCFG10 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG11: SOURCE=0 */
	DMAMUX_CHCFG11 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG12: SOURCE=0 */
	DMAMUX_CHCFG12 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG13: SOURCE=0 */
	DMAMUX_CHCFG13 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG14: SOURCE=0 */
	DMAMUX_CHCFG14 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* DMAMUX_CHCFG15: SOURCE=0 */
	DMAMUX_CHCFG15 &= (uint8_t)~(uint8_t)(DMAMUX_CHCFG_SOURCE(0x3F));
	/* ADC0_SC2: REFSEL=0 */
	ADC0_SC2 &= (uint32_t)~(uint32_t)(ADC_SC2_REFSEL(0x03));
	/* PORTB_PCR0: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR0 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)  | (uint32_t)(
			PORT_PCR_MUX(0x01)
	);

	/* PORTB_PCR1: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR1 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PORTC_PCR2: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR2 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* SIM_SOPT7: ADC1ALTTRGEN=0,ADC0ALTTRGEN=0 */
	SIM_SOPT7 &= (uint32_t)~(uint32_t)(
			SIM_SOPT7_ADC1ALTTRGEN_MASK |
			SIM_SOPT7_ADC0ALTTRGEN_MASK
	);
	/* ADC1_SC2: REFSEL=0 */
	ADC1_SC2 &= (uint32_t)~(uint32_t)(ADC_SC2_REFSEL(0x03));
	/* PORTC_PCR6: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR6 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PORTC_PCR3: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR3 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)  | (uint32_t)(
			PORT_PCR_MUX(0x03)
	);
	/* SIM_SOPT4: FTM0TRG1SRC=0,FTM0TRG0SRC=0 */
	SIM_SOPT4 &= (uint32_t)~(uint32_t)(
			SIM_SOPT4_FTM0TRG1SRC_MASK |
			SIM_SOPT4_FTM0TRG0SRC_MASK
	);
	/* PORTA_PCR1: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
	PORTA_PCR1 = (uint32_t)((PORTA_PCR1 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01) |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	));
	/* PORTA_PCR2: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
	PORTA_PCR2 = (uint32_t)((PORTA_PCR2 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01) |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	));
	/* PORTB_PCR17: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR17 = (uint32_t)((PORTB_PCR17 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTC_PCR0: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR0 = (uint32_t)((PORTC_PCR0 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTC_PCR1: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR1 = (uint32_t)((PORTC_PCR1 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTC_PCR11: ISF=0,MUX=1,DSE=0,ODE=1,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR11 = (uint32_t)((PORTC_PCR11 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01) |
			PORT_PCR_ODE_MASK
	));
	/* PORTD_PCR0: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR0 = (uint32_t)((PORTD_PCR0 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTD_PCR1: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR1 = (uint32_t)((PORTD_PCR1 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTD_PCR4: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR4 = (uint32_t)((PORTD_PCR4 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTD_PCR5: ISF=0,MUX=1,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR5 = (uint32_t)((PORTD_PCR5 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x06) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x01)
	));
	/* PORTB_PCR2: ISF=0,MUX=2,DSE=0,ODE=1,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR2 = (uint32_t)((PORTB_PCR2 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x05) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x02) |
			PORT_PCR_ODE_MASK
	));
	/* PORTB_PCR3: ISF=0,MUX=2,DSE=0,ODE=1,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR3 = (uint32_t)((PORTB_PCR3 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x05) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x02) |
			PORT_PCR_ODE_MASK
	));
	/* PORTC_PCR10: ISF=0,MUX=2,DSE=0,ODE=1,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR10 = (uint32_t)((PORTC_PCR10 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x05) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x02) |
			PORT_PCR_ODE_MASK
	));
	/* PORTC_PCR8: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR8 = (uint32_t)((PORTC_PCR8 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x03) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x04)
	));
	/* PORTC_PCR9: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR9 = (uint32_t)((PORTC_PCR9 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x03) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x04)
	));
	/* PORTC_PCR7: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR7 = (uint32_t)((PORTC_PCR7 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x03) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x04)
	));
	/* PORTC_PCR5: ISF=0,MUX=4,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR5 = (uint32_t)((PORTC_PCR5 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x03) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x04)
	));
	/* PORTA_PCR5: ISF=0,MUX=6,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=1 */
	PORTA_PCR5 = (uint32_t)((PORTA_PCR5 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x01) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x06) |
			PORT_PCR_PS_MASK
	));
	/* PORTA_PCR13: ISF=0,MUX=6,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTA_PCR13 = (uint32_t)((PORTA_PCR13 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x01) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x06)
	));
	/* PORTA_PCR12: ISF=0,MUX=6,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTA_PCR12 = (uint32_t)((PORTA_PCR12 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x01) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x06)
	));
	/* PORTA_PCR0: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTA_PCR0 = (uint32_t)((PORTA_PCR0 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x07)
	));
	/* PORTA_PCR3: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
	PORTA_PCR3 = (uint32_t)((PORTA_PCR3 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x07) |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	));
	/* PORTA_PCR18: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTA_PCR18 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PORTA_PCR19: ISF=0,MUX=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTA_PCR19 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x07) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PDB0_DACINTC0: EXT=0 */
	PDB0_DACINTC0 &= (uint32_t)~(uint32_t)(PDB_INTC_EXT_MASK);
	/* PDB0_DACINTC1: EXT=0 */
	PDB0_DACINTC1 &= (uint32_t)~(uint32_t)(PDB_INTC_EXT_MASK);
	/* PORTD_PCR3: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR3 = (uint32_t)((PORTD_PCR3 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x05) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x02)
	));
	/* PORTD_PCR2: ISF=0,MUX=2,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR2 = (uint32_t)((PORTD_PCR2 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x05) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x02)
	));
	/* PORTD_PCR7: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR7 = (uint32_t)((PORTD_PCR7 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x07)
	));
	/* PORTD_PCR6: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTD_PCR6 = (uint32_t)((PORTD_PCR6 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x07)
	));
	/* PORTE_PCR1: ISF=0,MUX=3,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTE_PCR1 = (uint32_t)((PORTE_PCR1 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x04) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	))); /* | (uint32_t)(
                PORT_PCR_MUX(0x03)
               ));*/
               /* PORTE_PCR0: ISF=0,MUX=3,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTE_PCR0 = (uint32_t)((PORTE_PCR0 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_MUX(0x04) |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	)));/* | (uint32_t)(
                PORT_PCR_MUX(0x03)
               ));*/
               /* PORTA_PCR4: ISF=0,MUX=7,DSE=0,ODE=0,PFE=0,SRE=0,PE=1,PS=1 */
	PORTA_PCR4 = (uint32_t)((PORTA_PCR4 & (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK
	)) | (uint32_t)(
			PORT_PCR_MUX(0x07) |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	));
	/* PORTB_PCR16: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR16 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PORTB_PCR18: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR18 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PORTB_PCR19: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTB_PCR19 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	);
	/* PORTC_PCR4: ISF=0,DSE=0,ODE=0,PFE=0,SRE=0,PE=0,PS=0 */
	PORTC_PCR4 &= (uint32_t)~(uint32_t)(
			PORT_PCR_ISF_MASK |
			PORT_PCR_DSE_MASK |
			PORT_PCR_ODE_MASK |
			PORT_PCR_PFE_MASK |
			PORT_PCR_SRE_MASK |
			PORT_PCR_PE_MASK |
			PORT_PCR_PS_MASK
	) | (uint32_t)(
			PORT_PCR_MUX(0x03)
	);

	/* PORTD_DFER: DFE&=~0xFF */
	PORTD_DFER &= (uint32_t)~(uint32_t)(PORT_DFER_DFE(0xFF));
}


/* END pin_mux. */
/*!
 ** @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Processor Expert 10.4 [05.11]
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */
