/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : I2C0.h
**     Project     : SignalGenerator
**     Processor   : MK22FN512VLH12
**     Component   : Init_I2C
**     Version     : Component 01.008, Driver 01.08, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-13, 15:17, # CodeGen: 7
**     Abstract    :
**          This file implements the I2C (I2C0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : I2C0
**          Device                                         : I2C0
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Clock setting                                : 
**              Multiplier factor                          : divide by 4
**              Clock rate                                 : 16
**              SCL frequency                              : 312.500 kHz
**              SDA hold value                             : 0.600 us
**              Slave baud rate control                    : Disabled
**              SCL low timeout counter clock select       : Bus clock/64
**              SCL low timout counter                     : 0
**              SCL low timeout                            : STOP
**            General call address                         : Disabled
**            Address mode                                 : 7-bit addressing
**            Slave address                                : 0
**            Transfer direction                           : Receive
**            Transmit Acknowledge                         : yes
**            Fast acknowledge                             : Disabled
**            Wake-up                                      : Disabled
**            Noise (glitch) filter factor                 : 0
**            Alert response address                       : Disabled
**            Second address                               : Disabled
**            Second address value                         : 97
**            Range address matching                       : Disabled
**            Range address                                : 0
**            Stop hold                                    : Disabled
**          Pins                                           : 
**            SDA pin allocation                           : Enabled
**              SDA pin                                    : ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/FTM1_QD_PHB
**              SDA pin signal                             : 
**            SCL pin allocation                           : Enabled
**              SCL pin                                    : ADC0_SE8/ADC1_SE8/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA
**              SCL pin signal                             : 
**            High drive select                            : Disabled
**          Interrupts/DMA                                 : 
**            I2C interrupt/DMA                            : 
**              Interrupt                                  : INT_I2C0
**              Interrupt priority                         : 0
**              Interrupt request                          : disabled
**              ISR Name                                   : 
**              I2C interrupt request                      : Disabled
**              SDA low, SCL high timeout interrupt        : Disabled
**              Bus stop or start interrupt                : Disabled
**              I2C request type                           : Interrupt
**          Initialization                                 : 
**            Module enable                                : yes
**            Master/Slave mode select                     : Master
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void I2C0_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C0.h
** @version 01.08
** @brief
**          This file implements the I2C (I2C0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup I2C0_module I2C0 module documentation
**  @{
*/         

#ifndef I2C0_H_
#define I2C0_H_

/* MODULE I2C0. */

#include "I2C0_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define I2C0_Init I2C0_Init
/* PDD macros peripheral base address parameter */
#define I2C0_DEVICE I2C0_BASE_PTR

#ifdef __cplusplus
}
#endif

/* END I2C0. */
#endif /* #ifndef __I2C0_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/


